### ISSUE TITLE
Change name to hsds-validator

### ISSUE THREAD

**Issue by greggish** [spilio/openreferral-validator#2]
@spilio would it be hard to change the name to hsds_validator?

**Comment by xrysanthos** [comment]
@greggish if you want me to handle this you need to give me admin rights for this specific repo.  Otherwise you can rename it directly from repo Settings > Repository name > Rename.

**Comment by greggish** [comment]
Hrm, that sounded easy enough, though I couldn't find the Rename feature; i just gave ya all the rights, go ahead – and, thank you!!

**Comment by xrysanthos** [comment]
@greggish done.  Also changed the project docs link to the correct URL https://openreferral.github.io/hsds-validator/

**Comment by greggish** [comment]
Great! Are there other instances of that naming in this repo that we should change, or is this ready for me to share with the community as-is?

Thank you!!

**Comment by xrysanthos** [comment]
No, you're good to go.  All the docs refer to the component as HSDS validator so it's ok.
